module CoqBridge
  ( Person(..)
  , toCoqRecord
  , runRangeCheck
  ) where

import qualified Checker as C  -- generated by Coq extraction

data Person = Person { age :: Integer, income :: Integer } deriving (Show)

toCoqRecord :: Person -> C.DQ__Record
toCoqRecord (Person a i) = C.DQ__Build_Record a i

runRangeCheck :: [Person] -> Bool
runRangeCheck ps = C.check_ds_range (map toCoqRecord ps)
